name: sampleFlutterProject
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  sqflite: ^1.3.2+4
  fluttertoast: ^3.1.3
  flutter_svg: ^0.19.0
  cached_network_image: ^2.0.0
  flutter_redux: ^ 0.7.0 
  redux_persist_flutter: ^ 0.8.3 
  shared_preferences: ^0.5.1 
  path_provider: ^1.6.28
  flutter_launcher_icons: "^0.7.4"

flutter_icons:
  image_path_ios: "assets/images/jpegs/appLogo.jpeg"
  image_path_android: "assets/images/jpegs/appLogo.jpeg"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    # svg
  - assets/images/svgs/notification.svg
  - assets/images/svgs/profile.svg
  - assets/images/svgs/insight.svg
  - assets/images/svgs/home.svg
  - assets/images/svgs/like.svg
  - assets/images/svgs/play.svg
  - assets/images/svgs/image.svg
  - assets/images/svgs/clock.svg
  - assets/images/svgs/unsupported_file.svg
  - assets/images/webps/empty_state.webp
  - assets/json/data.json
  - assets/json/hashTag.json